spring:
  application:
    name: taisha-rangers2
  datasource:
    url: jdbc:h2:mem:mydb
    username: milomarten
    password: password
    driverClassName: org.h2.Driver

#persistence:
#  session-manager:
#    base-path: 'M:\Code\taisha-rangers2'

reminder:
  enabled: false
  far-off-session-threshold: -7d # for sessions far in the future, only send the message at this offset from the proposed start time
  submit-status-reminder-offset: -48h # ping all players who have not submitted if they can attend session at this offset from the proposed start time
  latest-submit-status-offset: -24h # don't allow players to /when to a time after this offset from the proposed start time
  session-start-reminder-offset: -15m # ping all players that session is about to start at this offset from the start time
  done-reminder-offset: 16h # ping the GM at this offset from the start time to use /done
  start-time-calculation-fake-offset: 2s # Wait this amount of time before firing off the start time calculation message